
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov  2 2025 11:16:00 IST (Nov  2 2025 05:46:00 UTC)

// Verification Directory fv/dac_1 

module dac_1(clk, digital_value, pwm_out);
  input clk;
  input [7:0] digital_value;
  output pwm_out;
  wire clk;
  wire [7:0] digital_value;
  wire pwm_out;
  wire [8:0] accumulator;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  DFFQX1 pwm_out_reg(.CK (clk), .D (accumulator[8]), .Q (pwm_out));
  DFFQX1 \accumulator_reg[8] (.CK (clk), .D (n_14), .Q
       (accumulator[8]));
  DFFQX1 \accumulator_reg[7] (.CK (clk), .D (n_15), .Q
       (accumulator[7]));
  ADDFXL g1022__2398(.A (digital_value[7]), .B (n_12), .CI
       (accumulator[7]), .CO (n_14), .S (n_15));
  DFFQX1 \accumulator_reg[6] (.CK (clk), .D (n_13), .Q
       (accumulator[6]));
  ADDFX1 g1024__5107(.A (n_10), .B (digital_value[6]), .CI
       (accumulator[6]), .CO (n_12), .S (n_13));
  DFFQX1 \accumulator_reg[5] (.CK (clk), .D (n_11), .Q
       (accumulator[5]));
  ADDFX1 g1026__6260(.A (n_8), .B (digital_value[5]), .CI
       (accumulator[5]), .CO (n_10), .S (n_11));
  DFFQX1 \accumulator_reg[4] (.CK (clk), .D (n_9), .Q (accumulator[4]));
  ADDFX1 g1028__4319(.A (n_6), .B (digital_value[4]), .CI
       (accumulator[4]), .CO (n_8), .S (n_9));
  DFFQX1 \accumulator_reg[3] (.CK (clk), .D (n_7), .Q (accumulator[3]));
  ADDFX1 g1030__8428(.A (n_4), .B (digital_value[3]), .CI
       (accumulator[3]), .CO (n_6), .S (n_7));
  DFFQX1 \accumulator_reg[2] (.CK (clk), .D (n_5), .Q (accumulator[2]));
  ADDFX1 g1032__5526(.A (n_2), .B (digital_value[2]), .CI
       (accumulator[2]), .CO (n_4), .S (n_5));
  DFFQX1 \accumulator_reg[1] (.CK (clk), .D (n_3), .Q (accumulator[1]));
  ADDFX1 g1034__6783(.A (n_0), .B (digital_value[1]), .CI
       (accumulator[1]), .CO (n_2), .S (n_3));
  DFFQX1 \accumulator_reg[0] (.CK (clk), .D (n_1), .Q (accumulator[0]));
  AOI2BB1X1 g1036__3680(.A0N (digital_value[0]), .A1N (accumulator[0]),
       .B0 (n_0), .Y (n_1));
  AND2X1 g1037__1617(.A (digital_value[0]), .B (accumulator[0]), .Y
       (n_0));
endmodule

